import React, { useState, useEffect, useCallback } from "react";
import { useAppContext } from "@/context/AppContext";
import { useProjectSettings } from "@/hooks/useProjectSettings";
import { useWorkspace } from "@/context/WorkspaceContext";
import { toast } from "@/components/ui/use-toast";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Separator } from "@/components/ui/separator";
import { PlusCircle, CheckCircle, XCircle } from "lucide-react";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "@/components/ui/alert-dialog";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { useCollectionBuilderService } from "@/hooks/api/useCollectionBuilderService";
import { Progress } from "@/components/ui/progress";
import { useDropzone } from "react-dropzone";
import { cn } from "@/lib/utils";

type CollectionBuilderProps = {
  solutionPrefix: string;
};

const CollectionBuilder: React.FC<CollectionBuilderProps> = ({
  solutionPrefix,
}) => {
  const { currentProject } = useAppContext();
  const { currentWorkspace } = useWorkspace();
  const { settings, isLoading: isLoadingSettings, saveProjectSettings } =
    useProjectSettings(solutionPrefix, currentProject?.name);
  const {
    useGetStages,
    useCreateStageMutation,
    useUpdateStageMutation,
    useDeleteStageMutation,
    useRunCollectionBuilderMutation,
    progress,
    isProcessing,
  } = useCollectionBuilderService();

  const {
    data: stages = [],
    isLoading: isLoadingStages,
    refetch: refetchStages,
  } = useGetStages(currentProject?.id);
  const createStageMutation = useCreateStageMutation();
  const updateStageMutation = useUpdateStageMutation();
  const deleteStageMutation = useDeleteStageMutation();
  const runCollectionBuilderMutation = useRunCollectionBuilderMutation();

  const [stageName, setStageName] = useState("");
  const [stageDescription, setStageDescription] = useState("");
  const [stageIndex, setStageIndex] = useState(stages.length + 1);
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [isEditMode, setIsEditMode] = useState(false);
  const [selectedStage, setSelectedStage] = useState<any>(null);
  const [feedMappingColumns, setFeedMappingColumns] = useState<string>("");
  const [feedType, setFeedType] = useState<string>("");
  const [feedSource, setFeedSource] = useState<string>("");
  const [feedColumn, setFeedColumn] = useState<string>("");
  const [feedCondition, setFeedCondition] = useState<string>("");
  const [feedValue, setFeedValue] = useState<string>("");
  const [feedAction, setFeedAction] = useState<string>("");
  const [feedActionValue, setFeedActionValue] = useState<string>("");
  const [feedActionColumn, setFeedActionColumn] = useState<string>("");
  const [feedActionCondition, setFeedActionCondition] = useState<string>("");
  const [feedActionConditionValue, setFeedActionConditionValue] =
    useState<string>("");
  const [feedActionConditionColumn, setFeedActionConditionColumn] =
    useState<string>("");
  const [feedActionConditionAction, setFeedActionConditionAction] =
    useState<string>("");
  const [feedActionConditionActionValue, setFeedActionConditionActionValue] =
    useState<string>("");
  const [feedActionConditionActionColumn,
    setFeedActionConditionActionColumn,] = useState<string>("");
  const [feedActionConditionActionCondition,
    setFeedActionConditionActionCondition,] = useState<string>("");
  const [feedActionConditionActionConditionValue,
    setFeedActionConditionActionConditionValue,] = useState<string>("");
  const [feedActionConditionActionConditionColumn,
    setFeedActionConditionActionConditionColumn,] = useState<string>("");
  const [feedActionConditionActionConditionAction,
    setFeedActionConditionActionConditionAction,] = useState<string>("");
  const [feedActionConditionActionConditionActionValue,
    setFeedActionConditionActionConditionActionValue,] = useState<string>("");
  const [feedActionConditionActionConditionActionColumn,
    setFeedActionConditionActionConditionActionColumn,] = useState<string>("");
  const [feedActionConditionActionConditionActionCondition,
    setFeedActionConditionActionConditionActionCondition,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionValue,
    setFeedActionConditionActionConditionActionConditionValue,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionColumn,
    setFeedActionConditionActionConditionActionConditionColumn,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionAction,
    setFeedActionConditionActionConditionActionConditionAction,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionValue,
    setFeedActionConditionActionConditionActionConditionActionValue,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionColumn,
    setFeedActionConditionActionConditionActionConditionActionColumn,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionCondition,
    setFeedActionConditionActionConditionActionConditionActionCondition,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionValue,
    setFeedActionConditionActionConditionActionConditionActionConditionValue,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionColumn,
    setFeedActionConditionActionConditionActionConditionActionConditionColumn,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionAction,
    setFeedActionConditionActionConditionActionConditionActionConditionAction,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionValue,
    setFeedActionConditionActionConditionActionConditionActionConditionActionValue,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionColumn,
    setFeedActionConditionActionConditionActionConditionActionConditionActionColumn,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionAction,
    setFeedActionConditionActionConditionActionConditionActionConditionActionAction,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionValue,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionValue,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionColumn,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionColumn,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionAction,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionAction,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionValue,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionValue,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionColumn,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionColumn,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionAction,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionAction,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionValueValue,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionValueValue,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionColumnColumn,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionColumnColumn,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionAction,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionAction,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionValue,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionValue,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionColumn,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionColumn,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionAction,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionAction,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionValue,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionValue,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionColumn,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionColumn,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionAction,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionAction,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionValue,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionValue,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionColumn,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionColumn,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionAction,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionAction,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionValue,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionValue,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionColumn,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionColumn,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionAction,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionAction,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionValue,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionValue,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionColumn,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionColumn,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionAction,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionAction,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionValue,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionValue,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumn,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumn,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionAction,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionAction,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionValue,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionValue,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumn,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumn,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionAction,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionAction,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionValue,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionValue,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumn,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumn,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionAction,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionAction,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionValue,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionValue,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumn,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumn,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionAction,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionAction,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionValue,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionValue,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumn,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumn,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionAction,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionAction,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionValue,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionValue,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumn,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumn,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionAction,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionAction,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionValue,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionValue,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumn,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumn,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionAction,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionAction,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionValue,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionValue,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumn,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumn,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionAction,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionAction,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionValue,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionValue,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumn,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumn,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumn,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumn,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumn,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumn,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumn,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumn,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumn,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumn,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumnColumn,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumnColumn,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumnColumnColumn,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumnColumnColumn,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumnColumnColumnColumn,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumnColumnColumnColumn,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumnColumnColumnColumnColumn,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumnColumnColumnColumnColumn,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumnColumnColumnColumnColumnColumn,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumnColumnColumnColumnColumnColumn,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumn,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumn,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumn,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumn,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumn,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumn,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumn,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumn,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumn,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumn,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumn,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumn,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumn,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumn,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumn,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumn,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumn,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumn,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumn,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumn,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumn,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumn,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumn,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumn,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumn,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumn,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumn,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumn,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumn,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumn,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumn,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumn,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumn,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumn,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumn,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumn,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumn,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumn,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumn,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumn,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumn,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumn,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumn,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumn,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumn,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumn,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumn,
    setFeedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumn,] = useState<string>("");
  const [feedActionConditionActionConditionActionConditionActionConditionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionActionColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumnColumn,
    setFeedAction
