// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vshkxxwocmoomljdfsrk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzaGt4eHdvY21vb21samRmc3JrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3OTAyNTMsImV4cCI6MjA2MjM2NjI1M30.tcG6jlIr3Lmhb6-D-bdc_B3-MRtAERh3jn2BDDdK24Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);